version: "3.8"
services:
  rust:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      PGUSER: postgres
      POSTGRES_DB: tasks
    ports: 
      - "5433:5432"
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: